version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: recipe_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./db:/var/lib/postgresql/data/:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
     - .env.prod

  app:
    container_name: recipe_app
    image: bifidokk/recipe-bot-app:latest
    ports:
      - ${API_PORT}:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod

  migrations:
    container_name: recipe_migrations
    image: bifidokk/recipe-bot-migrations:latest
    command: ["migrate", "apply", "--url", "${POSTGRES_MIGRATION_DSN}", "--dir", "file://migrations"]
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env.prod
  