on: [push]
name: Build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.23.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - run: go mod download
      - name: Build
        run: go build ./cmd/main.go
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60